### ISSUE TITLE
repo sync does not work as expected

### ISSUE THREAD

**Issue by tropxy** [I2SE/in-tech-sc-bsp#1]
Hey guys,

we found a minor issue with the interaction between repo sync and the manifest. It seems that if we edit the `default.xml` manifest and then we issue `repo sync`, repo will fetch the manifest that is currently set in this repository and wont use the one we locally had modified. The solution we found was to specify the manifest file we wanted to use for the sync with `repo sync -m default.xml`.

Is this the expected behaviour of `repo`? I would not expect we needed to specify the manifest file.

**Comment by mhei** [comment]
Yes, this is expected behavior: the repo tool was originially developed to keep a local development tree in sync with upstream, see `repo help sync` for detailed description. While I agree, that it feels unhandy, your solution seems to be the best available option.
