### ISSUE TITLE
Flash built image to EvachargeSE

### ISSUE THREAD

**Issue by huy-truong** [I2SE/in-tech-sc-bsp#2]
Hello there, 

Thanks to your repo, I can create an image for the Evacharge, however I don't now how to flash the image to the board. 
While I can use the provided mfgtools to flash the image that generated by  `stib`, here we have different structure the output.
Could you please share how to flash the yocto image on the board ?

Huy Truong,

**Comment by HauFei** [comment]
Dear @huy-truong,

For this issue, which is not directly related to the BSP itself, please contact us within our service desk, which is available via our chargebyte homepage. Thanks.

Regards, Hauke
