### ISSUE TITLE
Cannot build NodeJs for EvachargeSE

### ISSUE THREAD

**Issue by mbamefa** [I2SE/in-tech-sc-bsp#7]
Hello everybody,

I've been exploring Everest's features and am working on an EvachargeSE. I'm currently facing an issue building nodeJs (v16.20.2) because of the EvachargeSE CPU architecture, which doesn't seem to be supported.

Is there a way around this? Or perhaps a different version of nodeJs that can be built under Yocto Kirkstone?

**Comment by mhei** [comment]
According to my knowledge, only very old versions of NodeJS had support for this CPU - I don't remember exact versions.
But why do you need the NodeJS on the platform? Using only the C++ part could work.

**Comment by mbamefa** [comment]
Basically, I would like to run Everest, on EvachargeSE, with a configuration file that contains some simulation modules (JsCarSimulator, JsSlacSimulator and JsYetiSimulator) and I couldn't find C++ modules for the same functions. Do you have any suggestions to do something like that without NodeJs?

**Comment by mhei** [comment]
So you try to use the EVAcharge SE as an EV simulator? Maybe you could elaborate on your intended setup and/or use-case. You are right, I'm also not aware of such simulation modules written in C++. But I still don't get it: as far as I understand, the mentioned modules are intended for use in SIL setups...

**Comment by mhei** [comment]
Closing due to no further feedback.
